//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Wrangler Sample Controller Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by codegen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroupPara) DeepCopyInto(out *AutoScalingGroupPara) {
	*out = *in
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroupPara.
func (in *AutoScalingGroupPara) DeepCopy() *AutoScalingGroupPara {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroupPara)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdvancedSettings) DeepCopyInto(out *ClusterAdvancedSettings) {
	*out = *in
	if in.KubeAPIServer != nil {
		in, out := &in.KubeAPIServer, &out.KubeAPIServer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KubeControllerManager != nil {
		in, out := &in.KubeControllerManager, &out.KubeControllerManager
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KubeScheduler != nil {
		in, out := &in.KubeScheduler, &out.KubeScheduler
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdvancedSettings.
func (in *ClusterAdvancedSettings) DeepCopy() *ClusterAdvancedSettings {
	if in == nil {
		return nil
	}
	out := new(ClusterAdvancedSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBasicSettings) DeepCopyInto(out *ClusterBasicSettings) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBasicSettings.
func (in *ClusterBasicSettings) DeepCopy() *ClusterBasicSettings {
	if in == nil {
		return nil
	}
	out := new(ClusterBasicSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCIDRSettings) DeepCopyInto(out *ClusterCIDRSettings) {
	*out = *in
	if in.EniSubnetIDs != nil {
		in, out := &in.EniSubnetIDs, &out.EniSubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCIDRSettings.
func (in *ClusterCIDRSettings) DeepCopy() *ClusterCIDRSettings {
	if in == nil {
		return nil
	}
	out := new(ClusterCIDRSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEndpoint) DeepCopyInto(out *ClusterEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEndpoint.
func (in *ClusterEndpoint) DeepCopy() *ClusterEndpoint {
	if in == nil {
		return nil
	}
	out := new(ClusterEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDisk) DeepCopyInto(out *DataDisk) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDisk.
func (in *DataDisk) DeepCopy() *DataDisk {
	if in == nil {
		return nil
	}
	out := new(DataDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionAddon) DeepCopyInto(out *ExtensionAddon) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionAddon.
func (in *ExtensionAddon) DeepCopy() *ExtensionAddon {
	if in == nil {
		return nil
	}
	out := new(ExtensionAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchConfigurePara) DeepCopyInto(out *LaunchConfigurePara) {
	*out = *in
	out.SystemDisk = in.SystemDisk
	if in.DataDisks != nil {
		in, out := &in.DataDisks, &out.DataDisks
		*out = make([]DataDisk, len(*in))
		copy(*out, *in)
	}
	if in.KeyIDs != nil {
		in, out := &in.KeyIDs, &out.KeyIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchConfigurePara.
func (in *LaunchConfigurePara) DeepCopy() *LaunchConfigurePara {
	if in == nil {
		return nil
	}
	out := new(LaunchConfigurePara)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolDetail) DeepCopyInto(out *NodePoolDetail) {
	*out = *in
	in.AutoScalingGroupPara.DeepCopyInto(&out.AutoScalingGroupPara)
	in.LaunchConfigurePara.DeepCopyInto(&out.LaunchConfigurePara)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolDetail.
func (in *NodePoolDetail) DeepCopy() *NodePoolDetail {
	if in == nil {
		return nil
	}
	out := new(NodePoolDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunInstancesForNode) DeepCopyInto(out *RunInstancesForNode) {
	*out = *in
	out.SystemDisk = in.SystemDisk
	if in.KeyIDs != nil {
		in, out := &in.KeyIDs, &out.KeyIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunInstancesForNode.
func (in *RunInstancesForNode) DeepCopy() *RunInstancesForNode {
	if in == nil {
		return nil
	}
	out := new(RunInstancesForNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TKEClusterConfig) DeepCopyInto(out *TKEClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TKEClusterConfig.
func (in *TKEClusterConfig) DeepCopy() *TKEClusterConfig {
	if in == nil {
		return nil
	}
	out := new(TKEClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TKEClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TKEClusterConfigList) DeepCopyInto(out *TKEClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TKEClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TKEClusterConfigList.
func (in *TKEClusterConfigList) DeepCopy() *TKEClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(TKEClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TKEClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TKEClusterConfigSpec) DeepCopyInto(out *TKEClusterConfigSpec) {
	*out = *in
	if in.ClusterEndpoint != nil {
		in, out := &in.ClusterEndpoint, &out.ClusterEndpoint
		*out = new(ClusterEndpoint)
		**out = **in
	}
	if in.ClusterBasicSettings != nil {
		in, out := &in.ClusterBasicSettings, &out.ClusterBasicSettings
		*out = new(ClusterBasicSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterCIDRSettings != nil {
		in, out := &in.ClusterCIDRSettings, &out.ClusterCIDRSettings
		*out = new(ClusterCIDRSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterAdvancedSettings != nil {
		in, out := &in.ClusterAdvancedSettings, &out.ClusterAdvancedSettings
		*out = new(ClusterAdvancedSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtensionAddon != nil {
		in, out := &in.ExtensionAddon, &out.ExtensionAddon
		*out = make([]ExtensionAddon, len(*in))
		copy(*out, *in)
	}
	if in.RunInstancesForNode != nil {
		in, out := &in.RunInstancesForNode, &out.RunInstancesForNode
		*out = new(RunInstancesForNode)
		(*in).DeepCopyInto(*out)
	}
	if in.NodePoolList != nil {
		in, out := &in.NodePoolList, &out.NodePoolList
		*out = make([]NodePoolDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VirtualNodePoolList != nil {
		in, out := &in.VirtualNodePoolList, &out.VirtualNodePoolList
		*out = make([]VirtualNodePoolDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TKEClusterConfigSpec.
func (in *TKEClusterConfigSpec) DeepCopy() *TKEClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TKEClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TKEClusterConfigStatus) DeepCopyInto(out *TKEClusterConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TKEClusterConfigStatus.
func (in *TKEClusterConfigStatus) DeepCopy() *TKEClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TKEClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNodeLabel) DeepCopyInto(out *VirtualNodeLabel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNodeLabel.
func (in *VirtualNodeLabel) DeepCopy() *VirtualNodeLabel {
	if in == nil {
		return nil
	}
	out := new(VirtualNodeLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNodePoolDetail) DeepCopyInto(out *VirtualNodePoolDetail) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]VirtualNodeLabel, len(*in))
		copy(*out, *in)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]VirtualNodeTaint, len(*in))
		copy(*out, *in)
	}
	if in.VirtualNodes != nil {
		in, out := &in.VirtualNodes, &out.VirtualNodes
		*out = make([]VirtualNodeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeletionProtection != nil {
		in, out := &in.DeletionProtection, &out.DeletionProtection
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNodePoolDetail.
func (in *VirtualNodePoolDetail) DeepCopy() *VirtualNodePoolDetail {
	if in == nil {
		return nil
	}
	out := new(VirtualNodePoolDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNodeSpec) DeepCopyInto(out *VirtualNodeSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]VirtualNodeTag, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNodeSpec.
func (in *VirtualNodeSpec) DeepCopy() *VirtualNodeSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNodeTag) DeepCopyInto(out *VirtualNodeTag) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNodeTag.
func (in *VirtualNodeTag) DeepCopy() *VirtualNodeTag {
	if in == nil {
		return nil
	}
	out := new(VirtualNodeTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNodeTaint) DeepCopyInto(out *VirtualNodeTaint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNodeTaint.
func (in *VirtualNodeTaint) DeepCopy() *VirtualNodeTaint {
	if in == nil {
		return nil
	}
	out := new(VirtualNodeTaint)
	in.DeepCopyInto(out)
	return out
}
